### ISSUE TITLE
RNA-DE numerator and denominator

### ISSUE THREAD

**Issue by eberdan** [bcbio/bcbioR#54]
In the params section both are preceded by a # which makes the user ignore them but they need to be set to load the data.

**Comment by eberdan** [comment]
Additionally, I had to manually call them to get the load function to work:

```r
numerator=params$numerator
denominator=params$denominator
``` 

These commands are present in the template but commented out as well.

**Comment by lpantano** [comment]
we are using list in the contrast variable to allow for multiple comparisons: 

`contrasts=list(c("sample_type", "tumor", "normal"))`
